[build]
  functions = "netlify/functions"
  publish = "dist"
  command = "npm run build"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/runtime-env"
  to = "/.netlify/functions/get-runtime-env"
  status = 200

[[redirects]]
  from = "/api/presign"
  to = "/.netlify/functions/presign-url"
  status = 200

[[redirects]]
  from = "/api/google-client-id"
  to = "/.netlify/functions/get-google-client-id"
  status = 200

[[redirects]]
  from = "/api/drive-list"
  to = "/.netlify/functions/drive-list"
  status = 200

[[redirects]]
  from = "/api/proxy-drive-image"
  to = "/.netlify/functions/proxy-drive-image"
  status = 200

[[redirects]]
  from = "/api/post-upload-process"
  to = "/.netlify/functions/post-upload-process"
  status = 200

[[redirects]]
  from = "/api/proxy-image"
  to = "/.netlify/functions/proxy-image"
  status = 200

[[redirects]]
  from = "/api/drive-upload"
  to = "/.netlify/functions/drive-upload"
  status = 200

[[redirects]]
  from = "/api/test-env"
  to = "/.netlify/functions/test-env"
  status = 200

[[redirects]]
  from = "/api/drive-upload-simple"
  to = "/.netlify/functions/drive-upload-simple"
  status = 200

[[redirects]]
  from = "/api/drive-upload-v2"
  to = "/.netlify/functions/drive-upload-v2"
  status = 200

[[redirects]]
  from = "/api/drive-upload-fixed"
  to = "/.netlify/functions/drive-upload-fixed"
  status = 200

[[redirects]]
  from = "/api/drive-upload-complete"
  to = "/.netlify/functions/drive-upload-complete"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18" 
